config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "dashboard", to: "pages#dashboard", as: "dashboard"
  namespace :owner do
    resources :costumes, only: %i[new create edit update destroy]
    resources :bookings, only: [] do
      member do
        patch :accept
        patch :decline
      end
    end
  end

  resources :costumes, only: [:index, :show] do
    resources :bookings, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :costume

  validates :start_date, :end_date, :total_price, :costume, :status, presence: true
  validates :status, inclusion: { in: %w[pending declined accepted] }

  validate :start_date_cannot_be_in_the_past, :end_date_must_be_after_start

  def start_date_cannot_be_in_the_past
    errors.add(:start_date, "can't be in the past") if
    !start_date.nil? && start_date < Date.today
  end

  def end_date_must_be_after_start
    errors.add(:end_date, "must be after start date") if
    !start_date.nil? && !end_date.nil? && end_date <= start_date
  end
end

app/models/costume.rb
class Costume < ApplicationRecord
  has_one_attached :photo
  belongs_to :owner, class_name: "User"
  has_many :bookings

  validates :price, :photo, :description, :title, presence: true
  validates :title, length: { minimum: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  has_many :costumes
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # CREATION DE NOUVEAU BOOKING
  def create
    @booking = Booking.new(booking_params)
    @costume = Costume.find(params[:costume_id])
    # On récupère la liste des bookings de cet user pour ce costume
    @user_bookings = @costume.bookings.where(user: current_user).sort_by(&:start_date)
    # On attribue le nouveau booking et à un costume et à un user
    @booking.costume = @costume
    @booking.user_id = current_user.id
    # Pour calculer le prix total, on vérifie la validité des dates rentrées
    if !@booking.start_date.nil? && !@booking.end_date.nil? && @booking.start_date < @booking.end_date
      @booking.total_price = (@booking.end_date - @booking.start_date).to_i * @booking.costume.price
    end
    # Par défaut, un booking créé a un statut Pending
    @booking.status = "pending"

    # Vérification d'enregistrement du booking pour redirection et message au User
    if @booking.save
      redirect_to costume_path(@booking.costume), notice: "Booking successfully created!"
    else
      render 'costumes/show', status: :unprocessable_entity
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/costumes_controller.rb
class CostumesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @costumes = Costume.all
    if params[:query].present?
      sql_subquery = "title ILIKE :query OR description ILIKE :query"
      @costumes = @costumes.where(sql_subquery, query: "%#{params[:query]}%")
    end
  end

  def show
    @costume = Costume.find(params[:id])
    @booking = Booking.new
    @user_bookings = @costume.bookings.where(user: current_user).sort_by(&:start_date)
  end
end

app/controllers/owner/bookings_controller.rb
class Owner::BookingsController < ApplicationController

  # ACCEPTER BOOKING
  def accept
    @booking = Booking.find(params[:id])
    @booking.status = "accepted"
    @booking.save
    redirect_to dashboard_path
  end

  # REFUSER BOOKING
  def decline
    @booking = Booking.find(params[:id])
    @booking.status = "declined"
    @booking.save
    redirect_to dashboard_path
  end
end

app/controllers/owner/costumes_controller.rb
class Owner::CostumesController < ApplicationController
  def new
    @costume = Costume.new
  end

  def create
    @costume = Costume.new(costume_params)
    @costume.owner = current_user
    if @costume.save
      redirect_to costume_path(@costume), notice: "Costume successfully added"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @costume = Costume.find(params[:id])
  end

  def update
    @costume = Costume.find(params[:id])
    @costume.update(costume_params)
    if @costume.save
      redirect_to dashboard_path, notice: "Costume successfully edited"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @costume = Costume.find(params[:id])
    if @costume.bookings.empty?
      @costume.destroy
      redirect_to dashboard_path, notice: "Costume deleted", status: :see_other
    else
      # A METTRE EN ALERTE (ROUGE)
      redirect_to dashboard_path, alert: "Costume cannot be deleted, you have booking on it!"
    end
  end

  private

  def costume_params
    params.require(:costume).permit(:title, :description, :price, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @costumes = Costume.all
    # @costume = Costume.find(params[:id])
    @costume1 = @costumes.sample
    @costume2 = @costumes.sample
    @costume2 = @costumes.sample until @costume2 != @costume1
  end

  def dashboard
    @user = current_user
    @user_bookings = @user.bookings
    @owner_bookings = Booking.joins(:costume).where(costumes: { owner_id: current_user.id })
    @owner_costumes = Costume.where(owner_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/costumes/index.html.erb
<%= render "shared/navbar" %>

<div class="pages-container">
  <h1 id="title-index">All ours costumes</h1>

  <p class='text-end'><%= link_to "Add Costume", new_owner_costume_path, class: "btn btn-gradient" %></p>
  <% if @costumes.any? %>
    <%# INDEX %>
    <ul class="costume-grid">
    <% @costumes.each do |costume| %>
      <li class="costume-card">
        <%= link_to costume_path(costume) do %>
            <%= cl_image_tag(costume.photo.key, width: 200, height: 200, crop: :fill, gravity: :face, class:"costume-photo") %>
            <h2 class="costume-name"><%= costume.title %></h2>
            <p id="costume-price-new"> <%= costume.price.round%> €</p>
        <% end %>
      </li>
    <% end %>
    </ul>
  <% else %>
    <h1 class="text-center py-5">Sorry, we don't have this costume yet!</h1>
  <% end %>

</div>

app/views/costumes/show.html.erb
<%= render "shared/navbar" %>
<%= render "shared/flashes" %>

<div class="pages-container">
  <%= link_to "Back to all costumes", costumes_path, class: "btn btn-secondary mt-3" %>

  <h1 class="mt-3 show-title"><%= @costume.title.capitalize %></h1>

  <div class="show-grid mt-3">
    <div class="show-card d-flex flex-row">
      <%= cl_image_tag(@costume.photo.key, width: 500, height: 350, crop: :fill, gravity: :face) %>
      <p class="mt-2 p-3"><%= @costume.description %></p>
    </div>

    <div class="show-card booking-card p-3">
      <p><em>Book it now!</em></p>
      <p class="fs-3"> <strong><%= @costume.price.round %>€</strong> per day</p>
      <%= simple_form_for [@costume, @booking] do |f| %>
        <%= f.input :start_date,
                    as: :string,
                    input_html: { data: { controller: "datepicker" } }
        %>
        <%= f.input :end_date,
                    as: :string,
                    input_html: { data: { controller: "datepicker" } }
        %>
        <%= f.submit "Create Booking", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>

  <div class="show-bookings mt-3">
    <%# Si l'user n'a pas de réservations sur ce costume, on le lui indique %>
    <% if @user_bookings == [] %>
    <h2 class="text-decoration-message">You don't have any booking for this costume :( </h2>
    <% else %>
      <%# S'il a des réservtions, on les affiche %>
      <h2 class="text-decoration-message">Your bookings for this costume</h2>
      <div class="d-flex gap-3 mt-3">
        <% if @user_bookings != nil %>
          <% @user_bookings.each do |b| %>
            <div class="bg-white card_width p-3 mb-3">

              <div class="d-flex justify-content-between">
                <p><em>in <%= (b.start_date - Date.today).to_i %> days!</em></p>
                  <%# condition pour l'status%>
                  <% if b.status == 'pending'%>
                      <p class="status-yellow">Pending</p>
                    <% elsif b.status == 'accepted'%>
                      <p class= "status-green">Accepted</p>
                    <% elsif b.status == 'declined' %>
                      <p class= "status-red">Declined</p>
                <% end %>
              </div>
              <div class="d-flex justify-content-between">
                <p>From <%= b.start_date %></p>
                <p>To <%= b.end_date %></p>
              </div>
                <p><i class="fa-solid fa-euro-sign"></i> <strong><%= b.total_price.round %></strong></p>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DisguiseYourself</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="min-vh-100">
      <%= yield %>
    </main>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/owner/costumes/edit.html.erb
<%= render "shared/navbar" %>
<h1 id="title-new">Edit Your Costume</h1>

<%= simple_form_for([:owner, @costume], html: { id: 'edit-costume-form', class: 'custom-form' }) do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.input :photo, as: :file %>
  <%= f.submit id: 'new-form-submit' %>
<% end %>

app/views/owner/costumes/new.html.erb
<%= render "shared/navbar" %>
<div class="container-new-owner">
  <h1 id="title-new">Create Costume</h1>
  <%= simple_form_for([:owner, @costume], html: { id: 'new-costume-form', class: 'custom-form' }) do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :photo, as: :file %>
    <%= f.submit id: 'new-form-submit' %>
  <% end %>
</div>

app/views/pages/dashboard.html.erb
<%= render "shared/navbarhome" %>

<%= render "shared/flashes" %>

<div class="container-dashboard pages-container" >
  <div class="d-flex justify-content-center mt-2"><img class="avatar-large" alt="avatar-large" src="https://kitt.lewagon.com/placeholder/users/arthur-littm" />
  </div>
  <h1 id="title-dashboard"> Hello <%= @user.username.capitalize  %> </h1>

  <div class="all-booking">
    <%#  Div Costume-rent by current_user  %>
    <div class="status-bookings">
      <h2 class="text-decoration">The costumes you're going to wear</h2>
        <div class="pending-bookings">
        <% if @user_bookings != [] %>
          <div id="pending-bloc"class="gap-1">
            <% if @user_bookings != nil %>
              <% @user_bookings.where(status: "accepted").each do |b| %>
                <div class="card-owner bg-white d-flex my-3">
                  <%= link_to costume_path(b.costume) do %>
                    <%=  cl_image_tag(b.costume.photo.key, width: 150, height: 150, crop: :fill, gravity: :face) %>
                  <% end %>
                  <div class="flex-grow-1 px-3 pt-3">
                    <div class="d-flex justify-content-between">
                      <p>From: <%= b.start_date %></p>
                      <p>To: <%= b.end_date %></p>
                    </div>
                    <div class="d-flex justify-content-between">
                      <%# condition pour l'status%>
                      <% if b.status == 'pending'%>
                        <p class="status-yellow">Pending</p>
                      <% elsif b.status == 'accepted'%>
                        <p class= "status-green">Accepted</p>
                      <% elsif b.status == 'declined' %>
                        <p class= "status-red">Declined</p>
                      <% end %>
                      <p><strong><%= b.total_price.round %>€</strong></p>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>

    <%# Status div avec pending et validates booking %>
    <div class="status-bookings">
      <%# Div des Owner Bookings status : "Pending" %>
      <div class="pending-bookings">
      <h3 class="text-center">Bookings on your costumes</h3>
        <% if @owner_bookings == [] %>
          <h2 class="text-secondary">You don't have any booking at this moment</h2>
        <% else %>
          <h4 class="mt-3 text-secondary">Pending bookings</h4>
          <div id="pending-bloc"class="gap-1">
            <% if @owner_bookings != nil %>
              <% @owner_bookings.where(status: "pending").each do |b| %>
                <div class="card-owner bg-white d-flex my-3">
                  <%= link_to costume_path(b.costume) do %>
                    <%=  cl_image_tag(b.costume.photo.key, width: 150, height: 150, crop: :fill, gravity: :face) %>
                  <% end %>
                  <div class="flex-grow-1 px-3 pt-3">
                    <div class="d-flex justify-content-between">
                      <p>From: <%= b.start_date %></p>
                      <p>To: <%= b.end_date %></p>
                    </div>
                    <div class="d-flex justify-content-between">
                      <p>Booked by <em><%= b.user.username %></em></p>
                      <p><strong><%= b.total_price.round %>€</strong></p>
                    </div>
                    <div class="d-flex justify-content-between">
                      <%= link_to "Accept", accept_owner_booking_path(b),class: "btn btn-outline-success w-50 me-1", data: { turbo_method: :patch} %>
                      <%= link_to "Decline", decline_owner_booking_path(b),class: "btn btn-outline-danger w-50 ms-1", data: { turbo_method: :patch} %>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>

      <%# Div des Owner Bookings status : "Accepted" %>
      <div class="pending-bookings">
        <% if @owner_bookings != [] %>
          <h4 class="mt-4 text-secondary">Validated bookings</h4>
          <div id="pending-bloc"class="gap-1">
            <% if @owner_bookings != nil %>
              <% @owner_bookings.where(status: "accepted").each do |b| %>
                <div class="card-owner bg-white d-flex my-3">
                  <%= link_to costume_path(b.costume) do %>
                    <%=  cl_image_tag(b.costume.photo.key, width: 150, height: 150, crop: :fill, gravity: :face) %>
                  <% end %>
                  <div class="flex-grow-1 px-3 pt-3">
                    <div class="d-flex justify-content-between">
                      <p>From: <%= b.start_date %></p>
                      <p>To: <%= b.end_date %></p>
                    </div>
                    <div class="d-flex justify-content-between">
                      <p>Booked by <em><%= b.user.username %></em></p>
                      <p><strong><%= b.total_price.round %>€</strong></p>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <%# All costumes you're selling %>
  <h2 id="title-owner-costumes">All your costume in the renting shop</h2>
  <div class="owner-costumes mb-3">
      <% @owner_costumes.each do |owner_costume| %>
        <div class="owner-costume-card">
          <%= link_to costume_path(owner_costume) do %>
            <div class="photo-card-owner">
              <%= cl_image_tag(owner_costume.photo.key, class: "rounded", width: 300, height: 200, crop: :fill, gravity: :face) %>
            </div>
            <% end %>
          <div class="description-owner-costume-card">
            <p><%= owner_costume.title %></p>
            <%# EDIT BUTTON %>
            <%= link_to '<i class="fa-solid fa-pen"></i>'.html_safe, edit_owner_costume_path(owner_costume), class: "me-4 text-black"%>
            <%# DELETE BUTTON %>
            <%= link_to '<i class="fa-solid fa-trash"></i>'.html_safe,
              owner_costume_path(owner_costume),
              data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
              class: "ms-4 text-danger"
            %>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<%= render "shared/navbar" %>
<div class="banner">
  <div class="container">
      <p class="mb-3 fs-2">Become who you've ever dreamed to be</p>
      <div class="costumecard">
          <%= link_to cl_image_tag(@costume1.photo.key, width: 300, height: 300, crop: :fill, gravity: :face), costume_path(@costume1) %>
          <%= link_to cl_image_tag(@costume2.photo.key, width: 300, height: 300, crop: :fill, gravity: :face), costume_path(@costume2) %>
      </div>
      <%= link_to "Find THE costume that suits you!", costumes_path, id:"btn-homepage" %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div>Made at Le Wagon Nantes</div>
  <div id="github-links">
    <p class="text-center mb-1">Check our github!</p>
    <div class="footer-links">
      <a href="https://github.com/maxlazz"><i class="fab fa-github"></i></a>
      <a href="https://github.com/kharns"><i class="fab fa-github"></i></a>
      <a href="https://github.com/brayan113018"><i class="fab fa-github"></i></a>
      <a href="https://github.com/nina44000"><i class="fab fa-github"></i></a>
    </div>
  </div>

  <div class="footer-copyright">
    DisguiseYourself Inc.
  </div>
</div>